version: '3'

services:
  agroism-dev:
    container_name: agroism-development
    environment:
      - PORT=5050
      - DEBUG=src*
    build: 
      context: .
      dockerfile: ./docker/Dockerfile.dev
    image: jiggliemon/agroism:develop
    volumes:
      - ./src:/root/src
      - /root/src/node_modules
    ports:
      - "5050:5050"
    command: ./bin/www
