FROM node:alpine

# Create app directory
WORKDIR /root/src

# Install nodemon for hot reload
RUN npm install -g nodemon

RUN echo 'alias ll="ls -n"' >> ~/.bashrc

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

RUN npm install --only=production

# Bundle app source
EXPOSE 5050

CMD ./bin/www